export const team = [
  {
    id: 1,
    name: "John Smith",
    role: "Founder & CEO",
    image: "/images/team/member-1.jpg",
    linkedin: "https://linkedin.com/",
    slug: "john-smith",
  },
  {
    id: 2,
    name: "Sarah Williams",
    role: "Creative Director",
    image: "/images/team/member-2.jpg",
    linkedin: "https://linkedin.com/",
    slug: "sarah-williams",
  },
  {
    id: 3,
    name: "David Miller",
    role: "Strategy Director",
    image: "/images/team/member-3.jpg",
    linkedin: "https://linkedin.com/",
    slug: "david-miller",
  },
  {
    id: 4,
    name: "Emma Brown",
    role: "Operations Director",
    image: "/images/team/member-4.jpg",
    linkedin: "https://linkedin.com/",
    slug: "emma-brown",
  },
  {
    id: 5,
    name: "Michael Johnson",
    role: "Brand Director",
    image: "/images/team/member-5.jpg",
    linkedin: "https://linkedin.com/",
    slug: "michael-johnson",
  },
  {
    id: 6,
    name: "Sophia Taylor",
    role: "Marketing Lead",
    image: "/images/team/member-6.jpg",
    linkedin: "https://linkedin.com/",
    slug: "sophia-taylor",
  },
];