// Case study summaries ported from the original fox.agency /work/ pages.
// Each card links out to the live case study on fox.agency (full write-ups aren't
// rebuilt as separate Next.js pages here yet).
export const allWorkArticles = [
  {
    title: "A different breed of awareness campaign",
    client: "Gamma",
    excerpt: "An award winning UK and European awareness campaign built on relationships.",
    image: "https://fox.agency/wp-content/uploads/2024/05/GAMMA_4-1-1024x512.png",
    href: "https://fox.agency/work/a-different-breed-of-awareness-campaign/",
  },
  {
    title: "A world of difference",
    client: "OVHcloud",
    excerpt: "Repositioning Europe’s largest cloud service provider… with a difference.",
    image: "https://fox.agency/wp-content/uploads/2024/05/OVHcloud-DOOH-display-horizontal-1.jpg",
    href: "https://fox.agency/work/a-world-of-difference/",
  },
  {
    title: "Accelerating ambition, unleashing a global brand",
    client: "Arcwide",
    excerpt: "Accelerating ambition for global IFS consultancy, Arcwide - launching a global brand with impact at IFS Unleashed, Miami Beach.",
    image: "https://fox.agency/wp-content/uploads/2023/05/Arcwide-large-format-out-of-home.jpg",
    href: "https://fox.agency/work/accelerating-ambition-unleashing-global-brand-arcwide/",
  },
  {
    title: "Advancing today, powering tomorrow",
    client: "PHINIA",
    excerpt: "Launching a truly global automotive brand for PHINIA.",
    image: "https://fox.agency/wp-content/uploads/2023/10/phinia-group-stock-change.jpg",
    href: "https://fox.agency/work/advancing-today-powering-tomorrow-phinia/",
  },
  {
    title: "An unbreakable bond",
    client: "tesa",
    excerpt: "Reaching, engaging, and expanding relationships with tier 1s and OEMs across global industry markets with tesa.",
    image: "https://fox.agency/wp-content/uploads/2025/02/Tesa-5-–-4-1024x512.png",
    href: "https://fox.agency/work/an-unbreakable-bond/",
  },
  {
    title: "Going further, faster, beyond",
    client: "Beyond Now",
    excerpt: "Beyond Now appointed Fox Agency to support its journey to becoming an independent entity and to create, and launch, a tech brand worthy of its global ambitions.",
    image: "https://fox.agency/wp-content/uploads/2023/05/BeyondNow-Website-Mockup.jpg",
    href: "https://fox.agency/work/beyond-now/",
  },
  {
    title: "Creating a transformational showcase event",
    client: "BOBST",
    excerpt: "BOBST DAYS envisioned the future of the global packaging industry in a digital showcase across 4 days of speakers, webinars and videos.",
    image: "https://fox.agency/wp-content/uploads/2023/07/bobst-days-website-landing-page-laptop-ui.jpg",
    href: "https://fox.agency/work/bobst-days/",
  },
  {
    title: "PHINIA Brand storytelling – A journey to tomorrow",
    excerpt: "See how we created an immersive, cinematic experience for PHINIA to unveil at Automechanika Frankfurt – the world’s leading automotive industry showcase.",
    image: "https://fox.agency/wp-content/uploads/2024/09/PHINIA-immersive-1920-x-960.png",
    href: "https://fox.agency/work/brand-storytelling-a-journey-to-tomorrow/",
  },
  {
    title: "Customer journeys to connected printing. We’re at their side.",
    client: "Brother",
    excerpt: "Brother were looking to bring new thinking to a B2B customer insight project at speed. Fox Agency implemented across digital & offline with messaging and creative assets that are ready-to-run across more than 30 European markets. ",
    image: "https://fox.agency/wp-content/uploads/2023/07/brother-website-screens-1.jpg",
    href: "https://fox.agency/work/brother/",
  },
  {
    title: "Capturing attention and opportunity",
    client: "Sony",
    excerpt: "Collaborating with Sony product and vertical market specialists, we undertook a full strategic analysis to achieve significant growth across European B2B markets.",
    image: "https://fox.agency/wp-content/uploads/2023/09/sony-hand-holidng-mobile-stacked-1-1.jpg",
    href: "https://fox.agency/work/capturing-attention-and-opportunity-sony/",
  },
  {
    title: "Capturing the best graduate talent",
    client: "Virgin Media",
    excerpt: "Promoting Virgin Media's graduate recruitment programme with an online ‘graduate hub’ and digital campaign to drive awareness and interest, and encourage graduates to join in the action.",
    image: "https://fox.agency/wp-content/uploads/2023/07/Virgin-capturing-graduate-talent-website-tablet-mobile-mocked-up.jpg",
    href: "https://fox.agency/work/capturing-graduate-talent-virgin-media/",
  },
  {
    title: "Respect builds growth",
    client: "Cassie",
    excerpt: "In a landscape where the changing face of personal data impacts brand-customer relationships & growth performance, we made Cassie’s CMP solution stand out.",
    image: "https://fox.agency/wp-content/uploads/2023/07/cassie-logo-and-social-media-mock-up.jpg",
    href: "https://fox.agency/work/cassie-website-rebrand/",
  },
  {
    title: "Sharing a vision for the fully autonomous future of construction",
    client: "Leica Geosystems",
    excerpt: "Using specialist 3D modelling, Fox Agency created a bespoke virtual world to help bring the future of construction sites to life for Leica Geosystems (part of the Hexagon AB Group).",
    image: "https://fox.agency/wp-content/uploads/2023/07/leica-creating-a-vision-for-the-future-of-global-construction-truck-digger.jpg",
    href: "https://fox.agency/work/creating-a-vision-for-the-future-of-global-construction/",
  },
  {
    title: "Creating opportunity: Be the Boss of AI",
    client: "BearingPoint",
    excerpt: "A pan-European awareness campaign with attitude.",
    image: "https://fox.agency/wp-content/uploads/2024/03/BP_AI-1-1-1024x512.png",
    href: "https://fox.agency/work/creating-opportunity-be-the-boss-of-ai/",
  },
  {
    title: "Customer onboarding, made epic",
    client: "Zenoo",
    excerpt: "Zenoo is challenging the way businesses onboard – with a transformational digital-first approach and a vision to make the customer journey smoother, slicker and more successful.",
    image: "https://fox.agency/wp-content/uploads/2023/05/ZENOO-come-onboard.jpg",
    href: "https://fox.agency/work/customer-onboarding-made-epic-zenoo/",
  },
  {
    title: "Digital transformation for packaging giants. Yep, that’s our bag",
    client: "BOBST",
    excerpt: "Fox Agency brings the creative & narrative, as well as the campaign strategies, digital initiatives, content, and campaign integration that positions BOBST as forward thinkers in the packaging industry.",
    image: "https://fox.agency/wp-content/uploads/2023/07/bobst-packaging-printing-machine-video-tablet-mocked-up.jpg",
    href: "https://fox.agency/work/digital-transformation-for-packaging-giants-yep-thats-our-bag/",
  },
  {
    title: "Driving performance across global markets",
    client: "intelliflo",
    excerpt: "Transforming the advisory experience across UK, US and Australia for intelliflo, the world-leading technology platform for the global financial advisory industry.",
    image: "https://fox.agency/wp-content/uploads/2024/09/Intelliflo-–-3.png.png",
    href: "https://fox.agency/work/driving-performance-across-global-markets/",
  },
  {
    title: "Empowering the next generation of managers, through the power of technology",
    client: "Piper",
    excerpt: "In a conglomerate of HR systems, Piper needed to stand out. See how we took them from new player to established thought-leader.",
    image: "https://fox.agency/wp-content/uploads/2023/05/Piper-article-mockup-unleash.jpg",
    href: "https://fox.agency/work/empowering-the-next-generation-piper/",
  },
  {
    title: "Enterprise AI, but not as you know it",
    client: "DataStax",
    excerpt: "Supercharging DataStax, a high-growth technology platform on a mission to increase brand visibility, brand awareness, and recall.",
    image: "https://fox.agency/wp-content/uploads/2025/06/DataStax-3-1024x512.png",
    href: "https://fox.agency/work/enterprise-ai-but-not-as-you-know-it/",
  },
  {
    title: "Everything in Motion",
    client: "Delphi",
    excerpt: "Succeeding in an industry undergoing unprecedented change requires a brand that can unify all the moving parts. See how we achieved it for Delphi.",
    image: "https://fox.agency/wp-content/uploads/2026/02/01-1920-x-960-–-14.png",
    href: "https://fox.agency/work/everything-in-motion/",
  },
  {
    title: "Grow with the flow",
    client: "Fellowes",
    excerpt: "To take their brand to new heights, Fellowes needed an elegant campaign that makes a serious impact. Read how we took monitor arms from practical to polished.",
    image: "https://fox.agency/wp-content/uploads/2023/07/fellowes-campaign-guidelines-on-ipad.jpg",
    href: "https://fox.agency/work/fellowes-brand-positioning/",
  },
  {
    title: "Future of mobile data",
    client: "BreatheSIM",
    excerpt: "Mobile data is evolving. Discover how we helped Manx Telecom corner the global travel data market by launching a new eSIM brand on the world stage.",
    image: "https://fox.agency/wp-content/uploads/2023/05/BreatheSIM-set-your-data-free-on-home-page.jpg",
    href: "https://fox.agency/work/future-of-mobile-data-breathesim/",
  },
  {
    title: "Precision engineering meets uber-targeted online communications",
    client: "Fenner Precision",
    excerpt: "Fox Agency were tasked with creating an online presence, reflective of a $1billion turnover corporation, coupled with communicating Fenner Precision’s custom-designed solutions to customers around the world.",
    image: "https://fox.agency/wp-content/uploads/2023/07/fenner-factory-components-cabinet-hand-holding-mesh.jpg",
    href: "https://fox.agency/work/global-website-project/",
  },
  {
    title: "Delphi how-to video production",
    excerpt: "See how we brought Delphi’s technology to life in a series of in-depth how-to videos.",
    image: "https://fox.agency/wp-content/uploads/2024/04/Challenger-brands-blog-post-_1200x627-1.png",
    href: "https://fox.agency/work/how-to-delphi-capturing-minute-details-in-incredibly-high-quality/",
  },
  {
    title: "Impact you can see",
    client: "A-Safe",
    excerpt: "Launching a new era of operational intelligence, safety, and performance with the global leader in industrial workspace safety, A-Safe.",
    image: "https://fox.agency/wp-content/uploads/2026/02/01-1920-x-960-–-4-1024x512.png",
    href: "https://fox.agency/work/impact-you-can-see/",
  },
  {
    title: "In the pursuit of excellence",
    client: "Textar",
    excerpt: "A global automotive brand campaign like no other.",
    image: "https://fox.agency/wp-content/uploads/2024/03/Textar-excellence-1.png",
    href: "https://fox.agency/work/in-the-pursuit-of-excellence/",
  },
  {
    title: "Launching a truly global fintech platform",
    client: "TruNarrative",
    excerpt: "Launching a global provider of fraud, identity and compliance solutions - TruNarrative. Working as a trusted partner to help create, launch and grow the brand across key global markets.",
    image: "https://fox.agency/wp-content/uploads/2023/07/tru-narrative-social-post-mockups.jpg",
    href: "https://fox.agency/work/launching-global-fintech-trunarrative/",
  },
  {
    title: "Launching the most powerful AML investigation platform",
    client: "Caspian",
    excerpt: "With new investment and huge growth ambitions, Caspian appointed Fox Agency to develop a unique brand, proposition and platform for launch across key global markets.",
    image: "https://fox.agency/wp-content/uploads/2023/07/Caspian-mobile-website.png",
    href: "https://fox.agency/work/launching-the-worlds-most-powerful-aml-investigation-platform/",
  },
  {
    title: "Mastering the automotive universe",
    client: "Delphi",
    excerpt: "Shifting gears, changing perceptions and putting brand storytelling into action for aftermarket parts manufacturer, Delphi.",
    image: "https://fox.agency/wp-content/uploads/2026/03/01-1920-x-960-–-14-1.png",
    href: "https://fox.agency/work/mastering-the-automotive-universe-delphi/",
  },
  {
    title: "A new reality for corporate hospitality",
    client: "Rendezverse",
    excerpt: "Explore a new reality for hospitality as we launch Rendezverse - the world's first AI-powered metaverse for the global hotels and events industry.",
    image: "https://fox.agency/wp-content/uploads/2023/05/RendexVerse-pr-phocus-wire-editorial.jpg",
    href: "https://fox.agency/work/new-reality-corporate-hospitality-rendezverse/",
  },
  {
    title: "One Global Platform. One Unified Story",
    client: "Abacus",
    excerpt: "One Global Platform. One Unified Story. See how Fox Agency helped Abacus unify its digital presence and launch a global website built for growth and credibility.",
    image: "https://fox.agency/wp-content/uploads/2026/04/01-1920-x-960-–-16-1.png",
    href: "https://fox.agency/work/one-platform-one-unified-story-abacus-group/",
  },
  {
    title: "Outsmarting the hyperscalers",
    client: "OVHcloud",
    excerpt: "The cloud sector is shifting fast. Accelerated by AI, hyperscalers are growing ever more dominant in the process.",
    image: "https://fox.agency/wp-content/uploads/2025/12/OVH-–-1_1920x960-1-1024x512.png",
    href: "https://fox.agency/work/outsmarting-the-hyperscalers/",
  },
  {
    title: "PHINIA’s inspiring leadership event",
    excerpt: "See how we created and executed an engaging day of innovation and excitement, at PHINIA’s inaugural leadership event – Momentum.",
    image: "https://fox.agency/wp-content/uploads/2024/03/Phinia_1200x627.png",
    href: "https://fox.agency/work/phinia-drone-show/",
  },
  {
    title: "Wellbeing: worth shouting about",
    excerpt: "The remote workplace means taking wellbeing on the road too. See how we helped Plumm lead the charge with a creative PR strategy.",
    image: "https://fox.agency/wp-content/uploads/2023/05/Plumm-article-mockup-diversityQ.jpg",
    href: "https://fox.agency/work/powering-mental-wellbeing-for-empowered-teams-plumm/",
  },
  {
    title: "Transforming language learning",
    client: "Berlitz",
    excerpt: "Fox Agency helped redefine global language services with our work for Bertliz. Our creative and design teams worked to create unique messaging and style themes to be used in print and online, created an integrated look. Find out how in our case study.",
    image: "https://fox.agency/wp-content/uploads/2023/07/berlitz-global-language-wall-graphic-office.jpg",
    href: "https://fox.agency/work/redefining-global-language-berlitz/",
  },
  {
    title: "Bringing customer research to life",
    client: "Brother Europe",
    excerpt: "Bringing B2B customer segmentation research to life for Brother Europe, to inform product planning, sales strategy and marketing and communications activity.",
    image: "https://fox.agency/wp-content/uploads/2023/07/brother-segmentation-research-communications-on-a-laptop-mocked-up-1.jpg",
    href: "https://fox.agency/work/segmentation-research-communications/",
  },
  {
    title: "Taking down dirty money",
    client: "Chorus Intelligence",
    excerpt: "Taking the market-leading law enforcement investigation platform and entering the global financial services market to finally get ahead of financial crime.​",
    image: "https://fox.agency/wp-content/uploads/2025/03/Chorus-3-1.png",
    href: "https://fox.agency/work/taking-down-dirty-money/",
  },
  {
    title: "Taking finance even further",
    client: "OneStream",
    excerpt: "Evolving OneStream from a quiet, highly capable platform into a visible, trusted and aspirational brand across global finance audiences.",
    image: "https://fox.agency/wp-content/uploads/2026/03/01-1920-x-960-–-14.png",
    href: "https://fox.agency/work/taking-finance-even-further-onestream/",
  },
  {
    title: "The Start OV Something Global",
    client: "Manx Telecom",
    excerpt: "The world of IoT is evolving fast and with this, comes huge opportunities for IoT Connectivity providers - like Manx Telecom.",
    image: "https://fox.agency/wp-content/uploads/2023/07/bobst-days-2021-the-future-of-the-packaging-world.jpg",
    href: "https://fox.agency/work/the-start-ov-something-global/",
  },
  {
    title: "Driving success for a global leader in automotive",
    client: "TMD Friction",
    excerpt: "Making TMD Friction look the very best in class at the most important automotive trade show on the planet, Automechanika Frankfurt.",
    image: "https://fox.agency/wp-content/uploads/2023/07/tmd-car-on-road-textar.jpg",
    href: "https://fox.agency/work/this-is-our-world-driving-global-automotive-success/",
  },
  {
    title: "Transformational content and creative for a global consultancy",
    client: "BearingPoint",
    excerpt: "Content, creative and digital activation for a global business transformation consultancy.",
    image: "https://fox.agency/wp-content/uploads/2023/05/BearingPoint-home-page-mockup.jpg",
    href: "https://fox.agency/work/transformational-communications-global-consultancy-bearingpoint/",
  },
  {
    title: "Translating innovation into headlines",
    client: "HydroGraph",
    excerpt: "Using PR strategy to translate innovation into headlines for HydroGraph, one of the world’s purest producers of graphene.",
    image: "https://fox.agency/wp-content/uploads/2025/07/Hydrograph-1.png",
    href: "https://fox.agency/work/translating-innovation-into-headlines/",
  },
  {
    title: "Turning up the heat",
    client: "IMI Hydronic Engineering",
    excerpt: "A tale of warm, smart homes and cold, hard results.",
    image: "https://fox.agency/wp-content/uploads/2024/06/IMI-4-–-3-1.png",
    href: "https://fox.agency/work/turning-up-the-heat/",
  },
  {
    title: "Unleashing the Power of the Possible",
    client: "BearingPoint",
    excerpt: "Fueling brand and demand in the US market for BearingPoint.",
    image: "https://fox.agency/wp-content/uploads/2023/12/bpus-desktop-device.png",
    href: "https://fox.agency/work/unleashing-the-power-of-the-possible/",
  },
  {
    title: "Unlocking the power of innovation",
    client: "Toshiba Tec",
    excerpt: "A pan-European launch to create opportunity and drive growth for A-BRID, Toshiba Tec's new, advanced operating system.",
    image: "https://fox.agency/wp-content/uploads/2025/01/Toshiba-–-2-1024x512.png",
    href: "https://fox.agency/work/unlocking-the-power-of-innovation/",
  },
  {
    title: "We are Generation Paper",
    client: "ABB",
    excerpt: "Strengthening the position of ABB as not only technology leader, but a committed and trusted industry partner with a deep understanding of the sector and a vision for the future.",
    image: "https://fox.agency/wp-content/uploads/2025/07/ABB-Generation-Paper-2-–-2-1.png",
    href: "https://fox.agency/work/we-are-generation-paper/",
  },
  {
    title: "Welcome to People-Powered EdTech",
    client: "Learnlight",
    excerpt: "Capitalising on opportunity to fuel exponential growth across global markets with language learning and soft skills training provider, Learnlight.",
    image: "https://fox.agency/wp-content/uploads/2025/04/Learnlight-–-3.png",
    href: "https://fox.agency/work/welcome-to-people-powered-edtech/",
  },
];
